name: mi_card_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
   - assetImages/p3.png
   - assetImages/p1.png
   - assetImages/p2.png
   - assetImages/p4.png
   - assetImages/p5.png
   - assetImages/p6.png
